import{a as C,S as q,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="49733836-ef97dcade25b1489c7fb046c8",S=15;async function P(o,t){return(await C.get("https://pixabay.com/api/",{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:S}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".gallery-button"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function B(o){const t=o.map(({largeImageURL:s,webformatURL:i,tags:e,likes:r,views:a,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${i}" alt="${e}" width="360" height="152" />
          </a>
          <ul class="gallery-info">
            <li class="gallery-info-item"><b>Likes</b> ${r}</li>
            <li class="gallery-info-item"><b>Views</b> ${a}</li>
            <li class="gallery-info-item"><b>Comments</b> ${L}</li>
            <li class="gallery-info-item"><b>Downloads</b> ${w}</li>
          </ul>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){m.innerHTML=""}function u(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}function x(){h.classList.remove("is-hidden")}function p(){h.classList.add("is-hidden")}const l="/goit-js-hw-12/assets/error-COYrvVuo.svg",g=document.querySelector(".form"),E=document.querySelector(".gallery-button");let c=1,f="";g.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim().toLowerCase();if(t===""){n.error({message:"Please enter a search query.",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:l});return}t!==f&&(f=t,c=1,O(),p()),await b(!0),g.reset()});E.addEventListener("click",async()=>{await b()});async function b(o=!1){u();try{const t=await P(f,c);if(t.hits.length===0&&o){n.error({message:"Sorry, there are no images matching<br/> your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:l});return}if(B(t.hits),c++,!o){const s=document.querySelector(".gallery .gallery-item");if(s){const i=s.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}t.hits.length===15?(x(),u()):(p(),n.show({message:"We're sorry, but you've reached the end of search results."}),d())}catch{n.error({message:"Something went wrong. Please try again later!",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff",class:"error-icon",iconUrl:l})}finally{d()}}
//# sourceMappingURL=index.js.map
